server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/tidygo
    username: root
    password: Thuy123!@#
